// <auto-generated />
using System;
using Lama.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Lama.Infrastructure.Migrations
{
    [DbContext(typeof(LamaDbContext))]
    [Migration("20260115115123_AddCompleteNamesNormalized")]
    partial class AddCompleteNamesNormalized
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Lama.Domain.Entities.Attendance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ConfirmedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ConfirmedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.Property<int?>("PointsAwardedPerMember")
                        .HasColumnType("int")
                        .HasColumnName("Points awarded per member");

                    b.Property<int?>("PointsPerDistance")
                        .HasColumnType("int")
                        .HasColumnName("Points per Distance");

                    b.Property<int?>("PointsPerEvent")
                        .HasColumnType("int")
                        .HasColumnName("Points per event");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("PENDING");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("VehicleId")
                        .HasColumnType("int");

                    b.Property<string>("VisitorClass")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Visitor Class");

                    b.HasKey("Id");

                    b.HasIndex("ConfirmedBy");

                    b.HasIndex("MemberId");

                    b.HasIndex("VehicleId");

                    b.HasIndex("EventId", "MemberId")
                        .IsUnique()
                        .HasDatabaseName("UQ_Attendance_MemberEvent");

                    b.ToTable("Attendance", (string)null);
                });

            modelBuilder.Entity("Lama.Domain.Entities.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Action")
                        .HasColumnType("int");

                    b.Property<string>("ActorExternalSubjectId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("ActorMemberId")
                        .HasColumnType("int");

                    b.Property<string>("AfterJson")
                        .HasColumnType("NVARCHAR(MAX)");

                    b.Property<string>("BeforeJson")
                        .HasColumnType("NVARCHAR(MAX)");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("EntityType")
                        .HasColumnType("int");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("CorrelationId")
                        .HasDatabaseName("IX_AuditLogs_CorrelationId");

                    b.HasIndex("TenantId", "CreatedAt")
                        .HasDatabaseName("IX_AuditLogs_TenantDate");

                    b.HasIndex("TenantId", "Action", "CreatedAt")
                        .HasDatabaseName("IX_AuditLogs_TenantActionDate");

                    b.HasIndex("TenantId", "ActorMemberId", "CreatedAt")
                        .HasDatabaseName("IX_AuditLogs_TenantMemberDate");

                    b.HasIndex("TenantId", "IpAddress", "CreatedAt")
                        .HasDatabaseName("IX_AuditLogs_TenantIpDate");

                    b.HasIndex("TenantId", "EntityType", "EntityId", "CreatedAt")
                        .HasDatabaseName("IX_AuditLogs_TenantEntityDate");

                    b.ToTable("AuditLogs", (string)null);
                });

            modelBuilder.Entity("Lama.Domain.Entities.Chapter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Chapters", (string)null);
                });

            modelBuilder.Entity("Lama.Domain.Entities.Configuration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("Configuration", (string)null);
                });

            modelBuilder.Entity("Lama.Domain.Entities.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChapterId")
                        .HasColumnType("int");

                    b.Property<int>("Class")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("EndLocationContinent")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EndLocationCountry")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateOnly>("EventStartDate")
                        .HasColumnType("date")
                        .HasColumnName("Event Start Date (AAAA/MM/DD)");

                    b.Property<double>("Mileage")
                        .HasColumnType("float")
                        .HasColumnName("Mileage");

                    b.Property<string>("NameOfTheEvent")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Name of the event");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<int>("PointsAwardedPerMember")
                        .HasColumnType("int")
                        .HasColumnName("Points awarded per member");

                    b.Property<int>("PointsPerDistance")
                        .HasColumnType("int")
                        .HasColumnName("Points per Distance");

                    b.Property<int>("PointsPerEvent")
                        .HasColumnType("int")
                        .HasColumnName("Points per event");

                    b.Property<string>("StartLocationContinent")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("StartLocationCountry")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("ChapterId");

                    b.ToTable("Events", (string)null);
                });

            modelBuilder.Entity("Lama.Domain.Entities.Evidence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AttendanceId")
                        .HasColumnType("int");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int?>("EventId")
                        .HasColumnType("int");

                    b.Property<string>("EvidenceType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.Property<string>("OdometerPhotoBlobPath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("OdometerReading")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("OdometerUnit")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Kilometers");

                    b.Property<string>("PilotPhotoBlobPath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ReviewNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReviewedBy")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("VehicleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AttendanceId")
                        .IsUnique()
                        .HasFilter("[AttendanceId] IS NOT NULL");

                    b.HasIndex("CorrelationId")
                        .IsUnique()
                        .HasDatabaseName("UX_Evidences_CorrelationId");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_Evidences_CreatedAt");

                    b.HasIndex("EventId");

                    b.HasIndex("MemberId");

                    b.HasIndex("VehicleId");

                    b.HasIndex("TenantId", "EventId")
                        .HasDatabaseName("IX_Evidences_TenantId_EventId");

                    b.HasIndex("TenantId", "MemberId")
                        .HasDatabaseName("IX_Evidences_TenantId_MemberId");

                    b.HasIndex("TenantId", "Status")
                        .HasDatabaseName("IX_Evidences_TenantId_Status");

                    b.HasIndex("TenantId", "VehicleId")
                        .HasDatabaseName("IX_Evidences_TenantId_VehicleId");

                    b.ToTable("Evidences", (string)null);
                });

            modelBuilder.Entity("Lama.Domain.Entities.IdentityUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ExternalSubjectId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("MemberId")
                        .HasColumnType("int");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_IdentityUsers_CreatedAt");

                    b.HasIndex("MemberId");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("IX_IdentityUsers_TenantId");

                    b.HasIndex("TenantId", "Email")
                        .HasDatabaseName("IX_IdentityUsers_TenantId_Email");

                    b.HasIndex("TenantId", "ExternalSubjectId")
                        .IsUnique()
                        .HasDatabaseName("UX_IdentityUsers_TenantId_ExternalSubjectId");

                    b.ToTable("IdentityUsers", (string)null);
                });

            modelBuilder.Entity("Lama.Domain.Entities.Member", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChapterId")
                        .HasColumnType("int");

                    b.Property<string>("CompleteNames")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName(" Complete Names");

                    b.Property<string>("CompleteNamesNormalized")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("CompleteNamesNormalized");

                    b.Property<string>("Continent")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CountryBirth")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Country Birth");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<bool>("Dama")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int?>("InLamaSince")
                        .HasColumnType("int")
                        .HasColumnName("In Lama Since");

                    b.Property<bool>("IsEligible")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("is_eligible");

                    b.Property<int?>("MemberStatusTypeStatusId")
                        .HasColumnType("int");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("STATUS");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("ChapterId");

                    b.HasIndex("CompleteNamesNormalized")
                        .HasDatabaseName("IX_Members_CompleteNamesNormalized");

                    b.HasIndex("MemberStatusTypeStatusId");

                    b.ToTable("Members", (string)null);
                });

            modelBuilder.Entity("Lama.Domain.Entities.MemberStatusType", b =>
                {
                    b.Property<int>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("StatusId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StatusId"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Category");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAt")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int")
                        .HasColumnName("DisplayOrder");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("IsActive");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("StatusName");

                    b.HasKey("StatusId");

                    b.HasIndex("DisplayOrder")
                        .HasDatabaseName("IX_MemberStatusTypes_DisplayOrder");

                    b.HasIndex("StatusName")
                        .IsUnique()
                        .HasDatabaseName("UQ_MemberStatusTypes_StatusName");

                    b.ToTable("MemberStatusTypes", (string)null);
                });

            modelBuilder.Entity("Lama.Domain.Entities.RankingSnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("EventsCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastCalculatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.Property<int?>("Rank")
                        .HasColumnType("int")
                        .HasComment("Posición en el ranking (1 = mejor)");

                    b.Property<string>("ScopeId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ScopeType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("TotalMiles")
                        .HasColumnType("float");

                    b.Property<int>("TotalPoints")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("VisitorClass")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LastCalculatedAt")
                        .HasDatabaseName("IX_RankingSnapshots_LastCalculatedAt");

                    b.HasIndex("MemberId")
                        .HasDatabaseName("IX_RankingSnapshots_MemberId");

                    b.HasIndex("Year", "CreatedAt")
                        .HasDatabaseName("IX_RankingSnapshots_Year_CreatedAt");

                    b.HasIndex("TenantId", "Year", "ScopeType", "ScopeId")
                        .HasDatabaseName("IX_RankingSnapshots_TenantYear_Scope");

                    b.HasIndex("TenantId", "Year", "ScopeType", "ScopeId", "MemberId")
                        .IsUnique()
                        .HasDatabaseName("UX_RankingSnapshots_TenantYear_Scope_Member");

                    b.HasIndex("TenantId", "Year", "ScopeType", "ScopeId", "TotalPoints")
                        .HasDatabaseName("IX_RankingSnapshots_Scope_Points");

                    b.ToTable("RankingSnapshots", (string)null);
                });

            modelBuilder.Entity("Lama.Domain.Entities.UserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AssignedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("AssignedBy")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExternalSubjectId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("AssignedAt")
                        .HasDatabaseName("IX_UserRoles_AssignedAt");

                    b.HasIndex("TenantId", "ExternalSubjectId")
                        .HasDatabaseName("IX_UserRoles_TenantId_ExternalSubjectId");

                    b.HasIndex("TenantId", "Role")
                        .HasDatabaseName("IX_UserRoles_TenantId_Role");

                    b.HasIndex("TenantId", "ExternalSubjectId", "IsActive")
                        .HasDatabaseName("IX_UserRoles_TenantId_ExternalSubjectId_IsActive");

                    b.ToTable("UserRoles", (string)null);
                });

            modelBuilder.Entity("Lama.Domain.Entities.UserScope", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AssignedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("AssignedBy")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExternalSubjectId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ScopeId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ScopeType")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("AssignedAt")
                        .HasDatabaseName("IX_UserScopes_AssignedAt");

                    b.HasIndex("TenantId", "ExternalSubjectId")
                        .HasDatabaseName("IX_UserScopes_TenantId_ExternalSubjectId");

                    b.HasIndex("TenantId", "ExternalSubjectId", "IsActive")
                        .HasDatabaseName("IX_UserScopes_TenantId_ExternalSubjectId_IsActive");

                    b.HasIndex("TenantId", "ExternalSubjectId", "ScopeType")
                        .HasDatabaseName("IX_UserScopes_TenantId_ExternalSubjectId_ScopeType");

                    b.HasIndex("TenantId", "ScopeType", "ScopeId")
                        .HasDatabaseName("IX_UserScopes_TenantId_ScopeType_ScopeId");

                    b.ToTable("UserScopes", (string)null);
                });

            modelBuilder.Entity("Lama.Domain.Entities.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("CutOffEvidenceUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CutOffEvidenceUrl");

                    b.Property<DateTime?>("CutOffEvidenceValidatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CutOffEvidenceValidatedAt");

                    b.Property<int?>("EvidenceValidatedBy")
                        .HasColumnType("int")
                        .HasColumnName("EvidenceValidatedBy");

                    b.Property<double?>("FinalOdometer")
                        .HasColumnType("float")
                        .HasColumnName("Final Odometer");

                    b.Property<DateOnly?>("FinalOdometerDate")
                        .HasColumnType("date")
                        .HasColumnName("Final Odometer Date");

                    b.Property<bool>("IsActiveForChampionship")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("LicPlate")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Lic Plate");

                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.Property<string>("MotorcycleData")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName(" Motorcycle Data");

                    b.Property<string>("OdometerUnit")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Miles")
                        .HasColumnName("OdometerUnit");

                    b.Property<string>("Photography")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("PENDING");

                    b.Property<string>("StartYearEvidenceUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("StartYearEvidenceUrl");

                    b.Property<DateTime?>("StartYearEvidenceValidatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("StartYearEvidenceValidatedAt");

                    b.Property<double?>("StartingOdometer")
                        .HasColumnType("float")
                        .HasColumnName("Starting Odometer");

                    b.Property<DateOnly?>("StartingOdometerDate")
                        .HasColumnType("date")
                        .HasColumnName("Starting Odometer Date");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Trike")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("Trike");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("EvidenceValidatedBy");

                    b.HasIndex("LicPlate")
                        .IsUnique();

                    b.HasIndex("MemberId");

                    b.ToTable("Vehicles", (string)null);
                });

            modelBuilder.Entity("Lama.Domain.Entities.Attendance", b =>
                {
                    b.HasOne("Lama.Domain.Entities.Member", "ConfirmedByMember")
                        .WithMany()
                        .HasForeignKey("ConfirmedBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Lama.Domain.Entities.Event", "Event")
                        .WithMany("Attendances")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lama.Domain.Entities.Member", "Member")
                        .WithMany("Attendances")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Lama.Domain.Entities.Vehicle", "Vehicle")
                        .WithMany("Attendances")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ConfirmedByMember");

                    b.Navigation("Event");

                    b.Navigation("Member");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("Lama.Domain.Entities.Event", b =>
                {
                    b.HasOne("Lama.Domain.Entities.Chapter", "Chapter")
                        .WithMany("Events")
                        .HasForeignKey("ChapterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Chapter");
                });

            modelBuilder.Entity("Lama.Domain.Entities.Evidence", b =>
                {
                    b.HasOne("Lama.Domain.Entities.Attendance", "Attendance")
                        .WithOne()
                        .HasForeignKey("Lama.Domain.Entities.Evidence", "AttendanceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Lama.Domain.Entities.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Lama.Domain.Entities.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Lama.Domain.Entities.Vehicle", "Vehicle")
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Attendance");

                    b.Navigation("Event");

                    b.Navigation("Member");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("Lama.Domain.Entities.IdentityUser", b =>
                {
                    b.HasOne("Lama.Domain.Entities.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Member");
                });

            modelBuilder.Entity("Lama.Domain.Entities.Member", b =>
                {
                    b.HasOne("Lama.Domain.Entities.Chapter", "Chapter")
                        .WithMany("Members")
                        .HasForeignKey("ChapterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Lama.Domain.Entities.MemberStatusType", null)
                        .WithMany("Members")
                        .HasForeignKey("MemberStatusTypeStatusId");

                    b.Navigation("Chapter");
                });

            modelBuilder.Entity("Lama.Domain.Entities.RankingSnapshot", b =>
                {
                    b.HasOne("Lama.Domain.Entities.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Member");
                });

            modelBuilder.Entity("Lama.Domain.Entities.Vehicle", b =>
                {
                    b.HasOne("Lama.Domain.Entities.Member", "ValidatedByMember")
                        .WithMany()
                        .HasForeignKey("EvidenceValidatedBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Lama.Domain.Entities.Member", "Member")
                        .WithMany("Vehicles")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Member");

                    b.Navigation("ValidatedByMember");
                });

            modelBuilder.Entity("Lama.Domain.Entities.Chapter", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("Members");
                });

            modelBuilder.Entity("Lama.Domain.Entities.Event", b =>
                {
                    b.Navigation("Attendances");
                });

            modelBuilder.Entity("Lama.Domain.Entities.Member", b =>
                {
                    b.Navigation("Attendances");

                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("Lama.Domain.Entities.MemberStatusType", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("Lama.Domain.Entities.Vehicle", b =>
                {
                    b.Navigation("Attendances");
                });
#pragma warning restore 612, 618
        }
    }
}
