-- Actualizar tabla MemberStatusTypes con TODOS los 33 valores de la lista desplegable
-- Basado en: Resumen!E4:E36 del archivo Excel

TRUNCATE TABLE [dbo].[MemberStatusTypes];

INSERT INTO [dbo].[MemberStatusTypes] ([StatusName], [Category], [DisplayOrder], [IsActive])
VALUES
-- NIVEL CAPÍTULO (9 valores)
('PROSPECT', 'CHAPTER', 1, 1),
('ROCKET PROSPECT', 'CHAPTER', 2, 1),
('FUL COLOR MEMBER', 'CHAPTER', 3, 1),
('CHAPTER PRESIDENT', 'CHAPTER_OFFICER', 10, 1),
('CHAPTER VICEPRESIDENT', 'CHAPTER_OFFICER', 11, 1),
('CHAPTER TREASURER', 'CHAPTER_OFFICER', 12, 1),
('CHAPTER BUSSINESS MANAGER', 'CHAPTER_OFFICER', 13, 1),
('CHAPTER SECRETARY', 'CHAPTER_OFFICER', 14, 1),
('CHAPTER MTO', 'CHAPTER_OFFICER', 15, 1),

-- NIVEL REGIONAL (6 valores)
('REGIONAL PRESIDENT', 'REGIONAL_OFFICER', 20, 1),
('REGIONAL VICEPRESIDENT', 'REGIONAL_OFFICER', 21, 1),
('REGIONAL TREASURER', 'REGIONAL_OFFICER', 22, 1),
('REGIONAL BUSSINESS MANAGER', 'REGIONAL_OFFICER', 23, 1),
('REGIONAL SECRETARY', 'REGIONAL_OFFICER', 24, 1),
('REGIONAL MTO', 'REGIONAL_OFFICER', 25, 1),

-- NIVEL NACIONAL (6 valores)
('NATIONAL PRESIDENT', 'NATIONAL_OFFICER', 30, 1),
('NATIONAL  VICEPRESIDENT', 'NATIONAL_OFFICER', 31, 1),
('NATIONAL TREASURER', 'NATIONAL_OFFICER', 32, 1),
('NATIONAL  BUSSINESS MANAGER', 'NATIONAL_OFFICER', 33, 1),
('NATIONAL  SECRETARY', 'NATIONAL_OFFICER', 34, 1),
('NATIONAL  MTO', 'NATIONAL_OFFICER', 35, 1),

-- NIVEL CONTINENTAL (6 valores)
('CONTINENTAL PRESIDENT', 'CONTINENTAL_OFFICER', 40, 1),
('CONTINENTAL VICEPRESIDENT', 'CONTINENTAL_OFFICER', 41, 1),
('CONTINENTAL TREASURER', 'CONTINENTAL_OFFICER', 42, 1),
('CONTINENTAL  BUSSINESS MANAGER', 'CONTINENTAL_OFFICER', 43, 1),
('CONTINENTAL SECRETARY', 'CONTINENTAL_OFFICER', 44, 1),
('CONTINENTAL MTO', 'CONTINENTAL_OFFICER', 45, 1),

-- NIVEL INTERNACIONAL (6 valores)
('INTERNATIONAL PRESIDENT', 'INTERNATIONAL_OFFICER', 50, 1),
('INTERNATIONAL  VICEPRESIDENT', 'INTERNATIONAL_OFFICER', 51, 1),
('INTERNATIONAL  TREASURER', 'INTERNATIONAL_OFFICER', 52, 1),
('INTERNATIONAL BUSSINESS MANAGER', 'INTERNATIONAL_OFFICER', 53, 1),
('INTERNATIONAL SECRETARY', 'INTERNATIONAL_OFFICER', 54, 1),
('INTERNATIONAL  MTO', 'INTERNATIONAL_OFFICER', 55, 1);

GO

SELECT [StatusId], [StatusName], [Category], [DisplayOrder]
FROM [dbo].[MemberStatusTypes]
ORDER BY [DisplayOrder];

GO

PRINT 'Tabla MemberStatusTypes actualizada con 33 valores de STATUS.';
